services:
    web:
        container_name: NITDA-web-app-cont-test
        build:
            context: ./services/web
            dockerfile: Dockerfile.dev
        restart: always
        x-develop:
            watch:
                - path: ./services/web/src/
                  target: app/src/
                  action: sync
                  ignore:
                      - /services/web/node_modules
                - path: /src/package.json
                  action: rebuild
        env_file:
            - ./services/web/src/.env
        ports:
            - 3000:3000
        healthcheck:
            test: exit 0
            retries: 3
        depends_on:
            api:
                condition: service_healthy
        volumes:
            - ./services/web/package.json:/usr/src/package.json

    api:
        container_name: NITDA-api-cont-test
        build:
            context: ./services/api
            dockerfile: Dockerfile.dev
        restart: always
        hostname: api
        x-develop:
            watch:
                - path: ./services/api/source/
                  target: source/
                  action: sync
                  ignore:
                      - ./services/api/node_modules
                - path: /src/package.json
                  action: rebuild
        healthcheck:
            test: exit 0
            retries: 3
        ports:
            - 5000:5000
            - 8000:8000
        depends_on:
            mongodb:
                condition: service_healthy
        volumes:
            - ./services/api/package.json:/usr/src/package.json

    mongodb:
        restart: always
        container_name: mongodb-cont-test
        image: mongo:latest
        hostname: mongodb
        healthcheck:
            test: exit 0
            retries: 3
        env_file:
            - ./services/api/.env
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB_DBNAME}
        volumes:
            - NITDA-mongodb-data-test:/data/db
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    mongo-express:
        image: mongo-express
        container_name: me-cont-test
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb-cont-test
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
            - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_DB_DBNAME}
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
        depends_on:
            mongodb:
                condition: service_healthy
        ports:
          - "8888:8081"
        volumes:
            - NITDA-mongodb-data-test:/data/db
volumes:
    NITDA-mongodb-data-test:








