services:
    web:
        container_name: NITDA-web-app-cont
        build: ./services/web
        restart: always
        env_file:
            - ./services/web/src/.env
        ports:
            - 3000:3000
        healthcheck:
            test: exit 0
            retries: 3
        depends_on:
            api:
                condition: service_healthy
        volumes:
            - ./services/web/package.json:/usr/src/package.json
    api:
        container_name: NITDA-api-cont
        build: ./services/api
        restart: always
        healthcheck:
            test: exit 0
            retries: 3
        env_file:
            - ./services/api/.env
        ports:
            - 5000:5000
        depends_on:
            mongodb:
                condition: service_healthy
        volumes:
            - ./services/api/package.json:/usr/src/package.json
    mongodb:
        restart: always
        container_name: mongodb-cont
        image: mongo:latest
        healthcheck:
            test: exit 0
            retries: 3

        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB_DBNAME}
        volumes:
            - ./services/api/db_backup/mongodb:/data/db
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
