FROM node:bullseye-slim

WORKDIR /usr/app

ADD package.json /usr/app/package.json

RUN yarn install

# add `/usr/app/node_modules/.bin` to $PATH
ENV PATH /usr/app/node_modules/.bin:$PATH

COPY . /usr/app

CMD [ "yarn", "dev" ]